### ISSUE TITLE
upload certificate validation fails 

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/certificateservice#8]
That's what you are trying to address now, right?

![image](https://github.com/cta-epfl/certificateservice/assets/3909535/0cae2c84-eec9-4d1b-a94f-be335ef2a8c2)

**Comment by Ph0tonic** [comment]
Yes, exactly.

**Comment by volodymyrss** [comment]
We agreed to make it possible to upload certificate with certificateservice. Then, when we figure out why our validation fails, we enable it back.

Let's keep the issue open until validation is working.

**Comment by Ph0tonic** [comment]
Just found this blog post while searching :

- https://www.netmeister.org/blog/debugging-certificate-errors.html

I will explore it more and try to debug using it next week.

**Comment by Ph0tonic** [comment]
Just found this blog post while searching :

- https://www.netmeister.org/blog/debugging-certificate-errors.html

I will explore it more and try to debug using it next week.

**Comment by volodymyrss** [comment]
Thanks! I thought it was working at some point before, wasn't it? Strange.

**Comment by Ph0tonic** [comment]
So, yes it was working but with your old certificate not the one provided by cern.

**Comment by volodymyrss** [comment]
> So, yes it was working but with your old certificate not the one provided by cern.

So the problem is in the CA?

**Comment by Ph0tonic** [comment]
Yes, I think so, maybe we are missing the CA used by cern to sign their certificate.
